version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    network_mode: host
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    image: postgres:13
    container_name: fastifyprisma
    network_mode: host
    restart: always
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: fastify-prisma
